### ISSUE TITLE
change build system to GN

### ISSUE THREAD

**Issue by snibug** [line/stellite#14]
latest chromium GYP build system was deprecated.
to adaptation latest chromium, stellite build have to follow a chromium's build system

**Comment by snibug** [comment]
https://github.com/line/stellite/commit/531037a91ed3a3e4f88bb3884d7dcf08b9882562

**Comment by snibug** [comment]
upgrade chromium tag 
52.0.2743.117 -> 56.0.2894.0

**Comment by snibug** [comment]
https://github.com/line/stellite/pull/17

**Comment by freakhill** [comment]
it is ok now i think no?

should we close this issue?

**Comment by snibug** [comment]
we can close this issue, if we upgrade chromium version over  56.0.2894.0

**Comment by ptyjj** [comment]
I have plan than upgrade chromium version.
buildsystem will be change to new system for latest chromium version.
