### ISSUE TITLE
Check failed cert_transparency_verifer_

### ISSUE THREAD

**Issue by snibug** [line/stellite#15]
[1201/142447:FATAL:ssl_client_socket_impl.cc(512)] Check failed: cert_transparency_verifier_. 

at master branch of stellite cannot request SSL/TLS because chromium SSLClientSocketImpl 
require initialize of cert_transparency_verifier setting

**Comment by freakhill** [comment]
is it still a bug?

**Comment by snibug** [comment]
no. this bug are resolved
