### ISSUE TITLE
build ios taraget,some problems occur

### ISSUE THREAD

**Issue by hutuyingxiong** [line/stellite#25]
File "./tools/build.py", line 1595, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./tools/build.py", line 1574, in main
    build.synchronize_chromium_tag()
  File "./tools/build.py", line 692, in synchronize_chromium_tag
    raise Exception('invalid chromium repository error')
Exception: invalid chromium repository error

**Comment by snibug** [comment]
@hutuyingxiong this look like that you abort or stop in build and retry.
so maybe you have to remove stellite/third_party directory it contain a chromium code.

**Comment by snibug** [comment]
we need to make stellite build script to leave a log to determine fetching chromium are complete or not.

**Comment by freakhill** [comment]
seems everything is ok here!
