### ISSUE TITLE
depot tools not on path when fetching

### ISSUE THREAD

**Issue by freakhill** [line/stellite#31]
error message:

![error message](https://cloud.githubusercontent.com/assets/916582/23215514/03eefea4-f956-11e6-9197-e67ecb1a721d.png)
 source code:

![incriminated source code](https://cloud.githubusercontent.com/assets/916582/23215521/0aa7b740-f956-11e6-8618-f75641b95f21.png)

currently working on a simple fix in tools/build.py

**Comment by freakhill** [comment]
on a test branch this dirty thingie seems to fix the problem

![image](https://cloud.githubusercontent.com/assets/916582/23215649/7c2bd11c-f956-11e6-8cd7-a37dc33b2c15.png)

**Comment by snibug** [comment]
looks great!

**Comment by snibug** [comment]
/github.com/line/stellite/issues/33

**Comment by snibug** [comment]
https://github.com/line/stellite/pull/37

**Comment by freakhill** [comment]
actually it is better to use os.pathsep

![image](https://cloud.githubusercontent.com/assets/916582/23298529/62b16758-fac1-11e6-8df9-b75421f3ac34.png)

https://docs.python.org/3/library/os.html#os.pathsep

**Comment by freakhill** [comment]
i'll send a pull request with pathsep later on :)
