### ISSUE TITLE
stellite on nodejs

### ISSUE THREAD

**Issue by snibug** [line/stellite#32]
developing quic server application there are some points of hardness.
first point is development performance. c/c++ is slow to develop API application compared to other language (javascript, java, php). so I'm thinking of putting the stellite QUIC server into script language.

currently, I'm thinking about alternative which is a javascript module that working on node js. and now much of it has been developed. this module is developed with stellite, chromium's QUIC, chromium's URL fetcher code that developed with c/c++. but it can be used with javascript.

this module will be provide with better quality than the HTTP/HTTPS module that provided by node standard library. because it is optimized in chromium

**Comment by notedit** [comment]
can not wait to have a test. 

when will we have this.

**Comment by snibug** [comment]
this time, node stellite is not mature. but if you want I'll pull request a mac version. for testing

**Comment by notedit** [comment]
ok  waiting your pull request

**Comment by snibug** [comment]
https://github.com/line/stellite/pull/35
