### ISSUE TITLE
setup CI stuff

### ISSUE THREAD

**Issue by freakhill** [line/stellite#33]
TODO

- setup build on our internal jenkins CI stuff
- add some nginx to export judge the badge part
- add the badge on the page

**Comment by freakhill** [comment]
for now just for linux

then we'll extend for other platforms once it's setup

**Comment by snibug** [comment]
excellent!!!!!!!!

**Comment by freakhill** [comment]
got basic build running, need to

- create an image to export badges jenkins badges
- integrate tests in the process
