### ISSUE TITLE
Failed to parse the certificate

### ISSUE THREAD

**Issue by bojin** [line/stellite#40]
I've built the stellite_quic_server_bin without any errors. But after that, the server doesn't want to start with the following error : 

> ./stellite_quic_server_bin --quic_port=443 --worker_count=48 --proxy_pass=http://127.0.0.1:80 --keyfile=../../../test_tools/res/example.com.cert.key --certfile=../../../test_tools/res/example.com.cert.pem --logging --log_dir=/var/log/stellite --file_logging
[0224/093027:INFO:stellite_quic_server_bin.cc(113)] quic server(443) start
[0224/093027:ERROR:quic_proxy_server.cc(49)] Failed to parse the certificate

I've tested with several different certificate and the same errors occurs. 
And is it possible to build stellite with openssl instead of nss ?

**Comment by snibug** [comment]
@bojin certificate file must use pkcs8. it can convert using openssl command-line tool.

**Comment by freakhill** [comment]
closing for now :)
