### ISSUE TITLE
I have error while building stellite on Ubuntu 14.04

### ISSUE THREAD

**Issue by bexp** [line/stellite#47]
~/stellite(master) $ tools/build.py --target-platform=linux --target stellite_http_client build
chromium is already exists: /home/deploy/stellite/third_party/chromium_linux
check chromium ...
check chromium tag ...
copy .gclient ...
copy modified_files ...
copy chromium/src/.gn ...
copy stellite files...
Running: ln -s /home/deploy/stellite/stellite
generate ninja script ...
Running: /home/deploy/stellite/third_party/depot_tools/gn gen /home/deploy/stellite/build_linux/src/out_linux
.gclient file in parent directory /home/deploy/stellite/build_linux might not be the file you want to use
Done. Made 407 targets from 101 files in 527ms
Running: /home/deploy/stellite/third_party/depot_tools/ninja -C /home/deploy/stellite/build_linux/src/out_linux stellite_http_client
ninja: Entering directory `/home/deploy/stellite/build_linux/src/out_linux'
[1/2051] CXX obj/base/base_paths/base_paths_posix.o
FAILED: obj/base/base_paths/base_paths_posix.o
../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/base/base_paths/base_paths_posix.o.d -DV8_DEPRECATION_WARNINGS -DENABLE_MDNS=1 -DENABLE_NOTIFICATIONS -DENABLE_PLUGINS=1 -DENABLE_PDF=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DUSE_UDEV -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_CLIPBOARD_AURAX11=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DENABLE_WEBRTC=1 -DENABLE_EXTENSIONS=1 -DENABLE_TASK_MANAGER=1 -DENABLE_THEMES=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_SUPERVISED_USERS=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DENABLE_MEDIA_ROUTER=1 -DFIELDTRIAL_TESTING_ENABLED -DCR_CLANG_REVISION=283753-1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DBASE_IMPLEMENTATION -I.. -Igen -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -B../third_party/binutils/Linux_x64/Release/bin -fcolor-diagnostics -fdebug-prefix-map=/home/deploy/stellite/build_linux/src=. -pthread -m64 -march=x86-64 -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-deprecated-register -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-shift-negative-value -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-address-of-packed-member -O2 -fno-ident -fdata-sections -ffunction-sections -g0 -fvisibility=hidden -Xclang -load -Xclang ../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wexit-time-destructors -fno-threadsafe-statics -fvisibility-inlines-hidden -std=gnu++11 -fno-rtti -fno-exceptions -c ../base/base_paths_posix.cc -o obj/base/base_paths/base_paths_posix.o
../base/base_paths_posix.cc:14:10: fatal error: 'memory' file not found
#include <memory>

**Comment by snibug** [comment]
chromium build are require that execution of $CHROMIUM_ROOT/src/build/install-build-deps.sh
this script will get dependencies.

**Comment by snibug** [comment]
@bexp we are patch https://github.com/line/stellite/pull/50/commits/a9ddf8f71176431afa7c679cb567eb0e4739af62
this will solve this issue
