### ISSUE TITLE
More frequent chromium updates?

### ISSUE THREAD

**Issue by krasic** [line/stellite#52]
Hi, I'm a member of the QUIC team at Google.  

We have a project [proto-quic](https://github.com/google/proto-quic) that like stellite, packages QUIC apart from Chromium.   We update it weekly against chromium, so it is usually no more than a week behind the chromium QUIC.   On the other hand, proto-quic is much more limited in terms of supported platforms and other enhancements that stellite provides.

Would you be interested in tracking chromium more closely?  We have the procedure semi-automated, and perhaps we could give you some ideas of how to do the same?

**Comment by krasic** [comment]
FYI, the scripts we use to sync proto-quic weekly are [here](https://github.com/google/proto-quic/tree/master/proto_quic_tools).

**Comment by snibug** [comment]
Hi @krasic.

This is a  interesting your suggestion. but stellite project are some problem to track a chromium lastest. stellite contain a executable or access chromium base, net package code like base::MessageLoop, net::URLFetcher that interface are changed sometime. that mean we cannot make it to automate or to semi-automate.

**Comment by snibug** [comment]
but we consider semi-update what you suggest. thanks!!
