### ISSUE TITLE
stellite linux server build error

### ISSUE THREAD

**Issue by dragonzhi** [line/stellite#57]
lz@lz:~/work/code/stellite$ ./tools/build.py --target-platform=linux --target stellite_quic_server_bin build
chromium is already exists: /home/lz/work/code/stellite/third_party/chromium_linux
check chromium ...
check chromium tag ...
copy .gclient ...
copy modified_files ...
copy chromium/src/.gn ...
copy node_binder files ...
Running: ln -s /home/lz/work/code/stellite/node_binder
copy stellite files...
Running: ln -s /home/lz/work/code/stellite/stellite
copya stellite build fakefiles ...
Running: ln -s /home/lz/work/code/stellite/build_linux/src/tools/vim/chromium.ycm_extra_conf.py /home/lz/work/code/stellite/.ycm_extra_conf.py
generate ninja script ...
Running: /home/lz/work/code/stellite/third_party/depot_tools/gn gen /home/lz/work/code/stellite/build_linux/src/out_linux/release
gn.py: Could not find gn executable at: /home/lz/work/code/stellite/build_linux/src/buildtools/linux64/gn
Traceback (most recent call last):
  File "./tools/build.py", line 2037, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./tools/build.py", line 2026, in main
    build.build()
  File "./tools/build.py", line 1707, in build
    self.generate_ninja_script(GN_ARGS_LINUX)
  File "./tools/build.py", line 829, in generate_ninja_script
    self.execute(command, cwd=self.buildspace_src_path)
  File "./tools/build.py", line 723, in execute
    raise Exception('command execution are failed')
Exception: command execution are failed

**Comment by dragonzhi** [comment]
Problem resolved.
should run: gclient runhooks

**Comment by ptyjj** [comment]
@dragonzhi 

do you resolved this problem?

I am working on build script for build problem.
Modified build script will be resolve this problem automatically.

**Comment by dsmlily** [comment]
@haru398801  how to modify the build script for the build problem?  Thanks
